SRCS:=$(wildcard *.c)                                                                                                                                                                                          
client:$(SRCS)
	gcc  $^ -o $@ -g -lcrypt 
clean:
	rm -rf client
