SRCS:=$(wildcard *.c)                                                                                                                                                                                          
server:$(SRCS)
	gcc  $^ -o $@ -lcrypt
clean:
	rm -rf server
